# file: .github/workflows/test1.yml
name: test1
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
        - uses: actions/checkout@v4
        - run: make setup
        - run: make test
        - run: make lint
